# Generated by Django 2.2.12 on 2022-01-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar_edit',
            name='name',
            field=models.CharField(default=2, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
