# Generated by Django 2.2.12 on 2022-01-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0003_first_page_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=150, unique=True)),
                ('Sub_Heading', models.CharField(max_length=150, unique=True)),
                ('Image', models.ImageField(upload_to='About_Update')),
                ('Website', models.CharField(max_length=150, unique=True)),
                ('City', models.CharField(max_length=150, unique=True)),
                ('Degree', models.CharField(max_length=150, unique=True)),
                ('Freelance', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
