# Generated by Django 2.2.12 on 2022-01-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0004_about_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, unique=True)),
                ('Icon', models.CharField(max_length=150, unique=True)),
                ('Name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='about_update',
            name='Email',
            field=models.EmailField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_update',
            name='Phone',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
