# Generated by Django 2.2.12 on 2022-01-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0007_auto_20220114_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interests_update',
            name='Title',
        ),
    ]
