# Generated by Django 2.2.12 on 2022-01-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0008_remove_interests_update_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, unique=True)),
                ('percentage', models.IntegerField()),
            ],
        ),
    ]
