# Generated by Django 2.2.12 on 2022-01-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0010_auto_20220114_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, unique=True)),
                ('Project_Name', models.CharField(max_length=150, unique=True)),
                ('Project_Specifications', models.CharField(max_length=150, unique=True)),
                ('Project_link', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
