# Generated by Django 2.2.12 on 2022-01-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0011_resume_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_projects',
            name='Title',
        ),
    ]
