# Generated by Django 2.2.12 on 2022-01-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0012_remove_resume_projects_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
