# Generated by Django 2.2.12 on 2022-01-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0013_myproject_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myproject_categories',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
