# Generated by Django 2.2.12 on 2022-01-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0014_auto_20220117_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myproject_categories',
            options={'ordering': ['Name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
