# Generated by Django 2.2.12 on 2022-01-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0015_auto_20220117_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myproject_categories',
            options={'ordering': ['Name'], 'verbose_name': 'category', 'verbose_name_plural': 'MyProjects_Categories'},
        ),
        migrations.CreateModel(
            name='MyProject_Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Image', models.ImageField(upload_to='MyProject_Update')),
                ('Project_Link', models.CharField(max_length=150, unique=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_portfolio.MyProject_categories')),
            ],
        ),
    ]
