# Generated by Django 2.2.12 on 2022-01-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0016_auto_20220117_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProjects_Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Image', models.ImageField(upload_to='MyProjects_Update')),
                ('Project_Link', models.CharField(max_length=150, unique=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_portfolio.MyProject_categories')),
            ],
        ),
        migrations.DeleteModel(
            name='MyProject_Update',
        ),
    ]
