# Generated by Django 2.2.12 on 2022-01-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0017_auto_20220117_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects_Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Projects_update')),
            ],
        ),
        migrations.DeleteModel(
            name='MyProjects_Update',
        ),
    ]
