# Generated by Django 2.2.12 on 2022-01-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0020_myproject_categories_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproject_categories',
            name='slug',
        ),
    ]
