# Generated by Django 2.2.12 on 2022-01-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0022_auto_20220118_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services_Icon', models.CharField(max_length=150, unique=True)),
                ('Services_Name', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
