# Generated by Django 2.2.12 on 2022-01-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0024_auto_20220118_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quotes', models.TextField()),
                ('Image', models.ImageField(upload_to='MyTeam')),
                ('Name', models.CharField(max_length=150, unique=True)),
                ('Position', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
