# Generated by Django 2.2.12 on 2022-01-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0026_auto_20220118_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=150, unique=True)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Call', models.CharField(max_length=150, unique=True)),
                ('Website', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
