# Generated by Django 2.2.12 on 2022-01-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0027_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_Update',
            new_name='About',
        ),
    ]
