# Generated by Django 2.2.12 on 2022-01-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0028_auto_20220118_0956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interests_update',
            new_name='Interests',
        ),
        migrations.RenameModel(
            old_name='Resume_Projects',
            new_name='Resume',
        ),
        migrations.RenameModel(
            old_name='Services_Update',
            new_name='Services',
        ),
        migrations.RenameModel(
            old_name='Skills_Update',
            new_name='Skills',
        ),
    ]
