# Generated by Django 2.2.12 on 2022-01-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0029_auto_20220118_0958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='First_page_edit',
            new_name='Home_Image',
        ),
    ]
