# Generated by Django 2.2.12 on 2022-01-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0031_about_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name1', models.CharField(max_length=150, unique=True)),
                ('Percentage1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name2', models.CharField(max_length=150, unique=True)),
                ('Percentage2', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
